spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080
  address: localhost